### PR TITLE
LPS-76286

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
Hey @arbetts, sending this to you since this is related to the work you did previously on LPS-54663.
See https://github.com/hhuijser/liferay-portal/pull/3113 for more information.

**Comment by yuhai** [comment]
Hi @arbetts

Hope you are well.

Since the issue came from EE customer. Do you have a chance to review this?

Regards,
Hai

**Comment by hhuijser** [comment]
Sent to @arboliveira instead: https://github.com/arboliveira/liferay-portal/pull/357

**Comment by arbetts** [comment]
@hhuijser @yuhai @arboliveira

was on PTO the last week. 

these changes look fine to me, but good to have @arboliviera take a look

**Pull request closed without merging**
