### PR TITLE
LPS-54544

### PR DESCRIPTION
**Pull request by danielkocsis**
Hey Andrew,

so finally I realized you did 2 things in the pull, the first is you fixed the issue properly, and the second is you created a maintenance task to clear the database from the preferences already left there.

I think the first part is great, but for the second one, could you please create a verify process instead? The code I think is totally reusable for that purpose, the only difference is the way how we invoke that. You can find an example for that in VerifySystemEvent.

thanks,
Daniel

### CODE REVIEW

**Comment by arbetts** [comment]
@danielkocsis 

Thanks for taking another look at this! I can move it into a verify and resend.

the reason I did not send it that way to begin with was because the clean up task will delete any runtime/embedded portletPreferences (since we can't distinguish between which portletPreferences are "orphaned" and which ones are embedded/runtime).

I wanted to give the users a choice to execute the clean up task; a verify will automatically do the clean up without notifying the user first.

do you still want me to put the cleanup in a VerifyProcess?

**Comment by danielkocsis** [comment]
Hey @arbetts,

As far as I can see the LayoutTypePortlet.getAllPortlets() can collect all to portlets from a layout including the embedded and static ones. So in theory we have the tool to get all the portlet id's, so there shouldn't be any side effect when running the verify process. 

Could you please check it?

If it woks, I think the verify process is a better, more widely used solution to mass update the leftovers in the database after a change. Also the user can disable to run verify processes with the verify.frequency=1 property.

thanks,
Daniel

**Comment by arbetts** [comment]
Thanks @danielkocsis 

I will look into using LayoutTypePortlet.getAllPortlets() and move this into a verify process.

thanks for the help
Andrew

**Comment by arbetts** [comment]
I didn't know if you were on PTO still so i sent the new pull through jonathan https://github.com/jonathanmccann/liferay-portal/pull/658

**Pull request closed without merging**
