### PR TITLE
LPS-52177

### PR DESCRIPTION
**Pull request by mhan810**

### CODE REVIEW

**Comment by mhan810** [comment]
@arbetts this should clean out the race condition

**Comment by mhan810** [comment]
@arbetts if this works, let me know.  We'll need to update the semantic version for portal-kernel as well before sending to BC

**Comment by arbetts** [comment]
@mhan810 this works. no more errors on startup and the company was deleted successfully

**Comment by arbetts** [comment]
@mhan810 were you going to forward to BC?

**Comment by mhan810** [comment]
Thought you were going to? ;)

Sent from my mobile device.

**Comment by arbetts** [comment]
ok ... i can do that ... thanks

**Comment by arbetts** [comment]
what do i need to change for the semantic versioning?

**Pull request closed without merging**
