### PR TITLE
LPS-63863 This seems like a better place to put this code, since it should only happen if the Group entry is going to be deleted. However I'm still a bit unhappy with so many if clauses. It would be better if we could simplify them further.

### PR DESCRIPTION
**Pull request by JorgeFerrer**
Hey Andrew, Here is a possible simplification of your fix. Take it as an example though, I haven't tested it

### CODE REVIEW

**Comment by arbetts** [comment]
I'll take another look at the flow of control logic inside the deleteGroup method to see if we can eliminate some of the branching.

**Comment by arbetts** [comment]
@JorgeFerrer 

taking another look at this; it seems like we can actually move the entire "// resources" block into the else statement like you did here: 48b574c

that solves any issues with removing resourcePermissions that we might still need. 

we are removing these resourcePermissions because they may be obsolete, but they will only become obsolete when the group itself is deleted. https://issues.liferay.com/browse/LPS-23333

**Comment by JorgeFerrer** [comment]
@arbetts I'm not sure about that. There are resources that need to be deleted since their associated entities are being deleted. Or am I missing something?

**Comment by arbetts** [comment]
@JorgeFerrer 

i've been doing research on this and happily came across our JavaDocs 
https://github.com/arbetts/liferay-portal/blob/master/portal-impl/src/com/liferay/portal/model/impl/ResourcePermissionImpl.java#L63-L78

This means that the code searching for the following permissions is actually trying to delete the Group Scope permissions for a given group. All the individual scoped permissions will have the primKey of the model and not the group, and the company has the companyId.

`List<ResourcePermission> resourcePermissions =
	resourcePermissionPersistence.findByC_LikeP(
		group.getCompanyId(), String.valueOf(group.getGroupId()));`

This means we can safely search for any Group scope permissions and delete those instead of doing a "like" search, which will incidentally include the individual resourcePermission of the group. The individual resourcePermission for the Group gets deleted when here:

`resourceLocalService.deleteResource(
	group.getCompanyId(), Group.class.getName(),
	ResourceConstants.SCOPE_INDIVIDUAL, group.getGroupId());`

so we would still be deleting this resourcePermission when applicable.

The new finder Method needed is:

`<finder name="C_S_P" return-type="Collection">
	<finder-column name="companyId" />
	<finder-column name="scope" />
	<finder-column name="primKey" />
</finder>`

so calling this method, and moving resourceLocalService.deleteResource( into the else block will fix the issue.

**Comment by JorgeFerrer** [comment]
Yup, that sounds much better.

Thanks @arbetts

**Comment by arbetts** [comment]
https://github.com/liferay/liferay-portal/pull/891

**Comment by arbetts** [comment]
https://github.com/JorgeFerrer/liferay-portal/pull/686

**Pull request closed without merging**
