### PR TITLE
LPS-47551

### PR DESCRIPTION
**Pull request by ligasm**
Hi. Could you have a look at the changes we made to the user service concerning to the null sort field. Is it OK? Also I have a problem with 2 method (see my last commit), they changed behaviour and do not search in the DB any more and use index. Due to the change the search fails to find results. Could you have a look at it? cc/ @mdelapenya

### CODE REVIEW

**Comment by ligasm** [comment]
Hi @mdelapenya and @arbetts

is there any progress on this?

**Comment by arbetts** [comment]
Hi @ligasm 

sorry, this got pushed back... i'll look at it today

**Comment by arbetts** [comment]
I could not run the tests because of errors. The module framework is not initializing correctly in my test environment

there are a few things that I see (i can't run the tests so I may not be right)
- the fix is commit 8007dfb 
- this fix uses the user_search_results.jspf
- the search method checks to see if the index can be used
- since the param "Inherit" is set to "true" then the search uses the DB instead of the index
- If no search results are coming up then I would look to verify that the Index is being used; the isCustomSQL(params) method will determine if the DB or Index is used.
- if you want to use the DB for a search in your tests then you need to either set the users.search.with.index property to false or add a parameter that the isCustomSQL() method doesn't recognize. params.put("useDB", "test") would work.
- It looks like the Sort doesn't impact the changes at all

since LPS-47551 was reported in 6.2.10 and the Sort changes are only in trunk, i think that those changes are not really affecting the fix.

I could be wrong because i am having trouble testing the changes, but I think the Sort part of the pull is working as intended.

**Comment by ligasm** [comment]
Hi @arbetts

My PR is not about the actual reported bug. The fix works fine and also the tests worked. The problem at hand is in the test methods (2ee4c00fb736a73cebe97958eff408f3a2681f3f).

Before the change did the methods use DB for getting the results and it worked fine but after the change the calls return different values. So the question is, if there should be something changed in the test or is there a bug. 
 
If the code does not work I can rebase the PR and send it again.

**Comment by arbetts** [comment]
Hi @ligasm 

thanks for the clarification! would you be able to rebase and then just update your branch ligasm:mdelapenya-LPS-47551

**Comment by ligasm** [comment]
Hi @arbetts 

I did the rebase and I pushed it to my branch. The mentioned tests still fail.

/cc @mdelapenya

**Comment by arbetts** [comment]
Thanks @ligasm 

I'm pulling the branch and will try to investigate the two methods that are failing

**Comment by arbetts** [comment]
when i run the test i still get the following error

23:04:50,476 ERROR [main][ServiceTestUtil:242] null
java.lang.NullPointerException
    at com.liferay.portal.security.ldap.LDAPSettingsUtil.isPasswordPolicyEnabled(LDAPSettingsUtil.java:98)
    at com.liferay.portal.service.impl.PasswordPolicyLocalServiceImpl.getDefaultPasswordPolicy(PasswordPolicyLocalServiceImpl.java:259)

**Comment by arbetts** [comment]
maybe @mdelapenya will have better luck looking into this

**Comment by ligasm** [comment]
Are you running all the tests or just UserServiceTest?

**Comment by arbetts** [comment]
just the UserServiceTest

I just migrated computers so I will have to double check my setup

**Comment by mdelapenya** [comment]
Hey guys, can you check your portal-test-ext? Verify that module.framework.initial.bundles property is not overriden.

If you debug ModuleFrameworkImpl._setupInitialBundles:130, the value of the constant MODULE_FRAMEWORK_INITIAL_BUNDLES must be "fileinstall.jar" (relative), which will be calculated by module framework.

**Pull request closed without merging**
