### PR TITLE
LPS-59712

### PR DESCRIPTION
**Pull request by danielkocsis**
Hey @arbetts,

this one only contains changes for LPS-59712. The only reason why I haven't sent it to Brian is that I am still not sure the JSON "structure" is really generic enough to fulfill everyone else's needs. I've checked the changes will happen in LPS-54744 and I feel this is still really staging based, although I am not really sure how could we generalize it even more, so I would like to discuss it with you. 

So currently (and in the future as well) we would like to support the option the developers can define custom details in JSON format. The current structure you defined is:

Details[header, status] -> Sections(s)[message] -> Item(s)[errormessage, errorstrongmessage, info]

So this structure seems pretty staging specific for me, to be honest.

Details[title] -> Section(s)[title, type??? {error, info}] -> item(s)[name, value]

What do you think? You are more into the code right now then me, so I am not sure how the current staging logic can fit into this?

Daniel

### CODE REVIEW

**Comment by arbetts** [comment]
@danielkocsis 

I may have an idea to make this more general. We might be able to use something similar to how the UserNotififcationHandlers create different notification markup.

it takes a template and then replaces the keys with the variable values. In this way we could define a template in the BackgroundTaskDisplay as well as maybe the JSON structure to expect, and then the Display object handles the key->value replace on the template... The tag could then just call some method like backgroundTaskDisplay.getDetails() 

does this sound like a good idea for generalizing the JSON section?

**Comment by danielkocsis** [comment]
As far as I can see currently we have 2 kinds of information regarding a background task:
- runtime information: progress, current operation, the object of the current operation. 
  For example: 42% Exporting XY article
- result information (currently it is 100% progress if there were no errors, or some error messages if there was any) status and statusMessage (we have a wrapper object BackgroundTaskResult for this)

The first one we can cover with a <background-task-progress-bar> tag

The second one although is the problematic one, since the developer can define any type of json objects. The thing I would like to avoid is to over engineer this tool, since the current API gives us a lot of freedom and the developer can do almost anything he wants. So what do you think about, that in the first step we just create the <background-task-progress-bar> tag, and add support to display the current operation and the item it is processing currently. These could be child tags to support formatting, usage of custom BTStatus attributes, etc.. And create only a pretty simple tag, that gives only backgroundTask.getStatusMessage() to the developer and in the tag body he can define his own logic to display this. 

<background-task-progress id="">
   <current-operation varName="status"><p>doing: <%= status.getAttr("operation") %> </p></current-operation>
    <current-item> ... </current-item>
</background-task-progress id="">
<background-task-result id="" varName="result">
    <% JSONObject jsonObj = JSONFactoryUtil.createJSONObject(result.getStatusMessage()); %>
   <p> <%= jsonObj.... %> </p>
</background-task-result>

And later we could extend this whole thing to support application display templates or DDM in general, but only if it is necessary! To avoid extra work or over engineering. 

What do you think?

I guess a progress bar, with some extra options and a tag to help to display the result would be a great help compared to the row status objects what we have currently.

**Comment by arbetts** [comment]
I was thinking of using free marker to make the details section, that way a developer can do whatever they want ... they define the ftl template in the BTD and pass the variables they need (along with some predefined ones) into the template. 

here is a pull as a rough draft of my idea:
https://github.com/danielkocsis/liferay-portal/pull/500

that pull has some of my debugging logic, so its just a rough idea, but i think i got it to work for staging.
It also only has one tag, since i was using some of my older changes... 

so in the final version its going to have a few different tags and the <background-task-status-details> tag is the one that will display the template... I don't see any problems with the other tags defining variables and the developer being able to use their own markup inside the body of those tags.

i'd like to move forward on a final version of this if you think its ok

thanks for all the help!!
-Andrew

**Comment by arbetts** [comment]
@danielkocsis 

have you had a chance to look at danielkocsis#500 ?

**Pull request closed without merging**
