### PR TITLE
LPS-64232

### PR DESCRIPTION
**Pull request by jorgediaz-lr**

### CODE REVIEW

**Comment by arbetts** [comment]
ci:retest

**Comment by arbetts** [comment]
@jorgediaz-lr failed to compile?

**Comment by jorgediaz-lr** [comment]
ci:retest

**Comment by jorgediaz-lr** [comment]
ci:retest

**Comment by arbetts** [comment]
I've cleaned up a few things about the initLanguageProperties method, but i don't think i've changed anything about your fix. i'll send you a pull with my changes and if everything still looks good, go ahead and forward it on.

I will take a look at your second pull later today (I'm sorry if my changes to this one means a rebase conflict)

https://github.com/jorgediaz-lr/liferay-portal/pull/40

**Pull request closed without merging**
