### PR TITLE
[TECHNICAL-SUPPORT] LPS-26811 Error in log when creating url with liferay-portlet:renderURL

### PR DESCRIPTION
**Pull request by lipusz**
https://issues.liferay.com/browse/LPS-26811

Hi Andrew,

This one has been pending in my queue for days due to my other tasks. Since you provided the guidance for Péter on the forum, could you please do the further review?

Thanks a lot!

Regards,
Tibor

/cc @peterborkuti

### CODE REVIEW

**Comment by arbetts** [comment]
@lipusz I can take a look.

who should i forward it to once i've had a chance to look at it?

**Comment by lipusz** [comment]
Ray or Shuyang I guess.

On Mon, Feb 29, 2016 at 7:23 PM, Andrew Betts <notifications@github.com>
wrote:

> @lipusz <https://github.com/lipusz> I can take a look.
>
> who should i forward it to once i've had a chance to look at it?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/arbetts/liferay-portal/pull/41#issuecomment-190320819>
> .
>



-- 

*Tibor LIPUSZ*

Sr. Software Engineer, Team Lead
SME of Search & Security
Subscription Services, EMEA


*Liferay Hungary Kft.* | H-1138 Budapest, Madarász Viktor u. 47. a-b.,
Hungary

*Visit Us: **www.liferay.com <http://www.liferay.com/>**  |  Like Us:
**facebook.com/liferay
<http://facebook.com/liferay>**  |  Follow Us: twitter.com/liferay
<http://twitter.com/liferay>*


* <http://twitter.com/liferay>*

<http://www.liferay.com>

**Comment by arbetts** [comment]
in review

**Comment by arbetts** [comment]
https://github.com/shuyangzhou/liferay-portal/pull/2633

**Pull request closed without merging**
